#################
### AUTOSTART ###
#################
exec-once = ~/.config/hypr/scripts/session-init
exec-once = hyprpaper
exec-once = ~/.local/bin/random-wall.sh
exec-once = waybar
exec-once = sleep 1 && hyprctl monitors | awk '/^Monitor/{if ($2 ~ /^eDP-/) print $2}' | while read -r m; do hyprctl keyword monitor "$m,disable"; done
