# ----- Cursor -----
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# ----- Theming -----
env = GTK_USE_PORTAL,1
env = GTK_THEME,adw-gtk3-dark

# ----- Session -----
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# ----- App toolkits (force Wayland) -----
env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland

# ----- XWayland -----
xwayland {
  force_zero_scaling = true
}
