# ============================================
# Hyprland — window rules
# ============================================

# ----- Ignore ghost/transient XWayland windows -----
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

# ----- Float dialogs & popups -----
windowrule = float on, match:class ^(pavucontrol|file_progress|confirm|dialog|download|notification|error|splash|confirmreset)$
windowrule = float on, match:title ^(Open File|Select a file|Choose Files|Save As|Library Preferences|Settings|Preferences|About)$
windowrule = float on, match:class ^(\(Cursor\))$

# ----- Size & position -----
windowrule = size 800 600, match:class ^(pavucontrol)$
windowrule = center on, match:class ^(pavucontrol)$

# ----- Effects -----
layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

windowrule = suppress_event fullscreen maximize, match:float true
