#!/bin/bash

set -euo pipefail

THEMES_DIR="$HOME/.config/themes"
CURRENT_THEME_LINK="$HOME/.config/themes/current/theme"

mapfile -t THEMES < <(find "$THEMES_DIR" -mindepth 1 -maxdepth 1 -type d | sort)
TOTAL=${#THEMES[@]:-0}

if (( TOTAL == 0 )); then
  echo "No themes found in $THEMES_DIR" >&2
  exit 1
fi

if [[ -L "$CURRENT_THEME_LINK" ]]; then
  CURRENT_THEME=$(realpath "$CURRENT_THEME_LINK")
else
  CURRENT_THEME=$(realpath "${THEMES[0]}")
fi

INDEX=0
for i in "${!THEMES[@]}"; do
  THEMES[i]=$(realpath "${THEMES[i]}")
  if [[ "${THEMES[i]}" == "$CURRENT_THEME" ]]; then
    INDEX=$i
    break
  fi
done

NEXT_INDEX=$(((INDEX + 1) % TOTAL))
NEW_THEME="${THEMES[$NEXT_INDEX]}"
NEW_THEME_NAME=$(basename "$NEW_THEME")

"$HOME/.config/hypr/scripts/theme-set" "$NEW_THEME_NAME"


