# Hyprland Configuration
# Modular config - each section in its own file

# Theme / Colors
source = ~/.config/hypr/hyprland/colors.conf

# Core
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/programs.conf
source = ~/.config/hypr/configs/environment.conf
source = ~/.config/hypr/configs/autostart.conf

# Appearance & Behavior
source = ~/.config/hypr/configs/look_and_feel.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybindings.conf
source = ~/.config/hypr/configs/window_rules.conf
