################
### COLORS ###
################
general {
    col.active_border = rgba(c0c6d5CC) rgba(929092CC) 45deg
    col.inactive_border = rgba(474648AA)
}

misc {
    background_color = rgba(131315FF)
    disable_hyprland_logo = true
    disable_splash_rendering = true
    font_family = Inter
}

# Pinned windows get a distinct border
windowrule = border_color rgba(c0c6d5EE) rgba(929092EE) 45deg, match:pin true
